apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prime
  name: prime
spec:
  replicas: 10
  selector:
    matchLabels:
      app: prime
  template:
    metadata:
      labels:
        app: prime
    spec:
      containers:
        - image: httpd:alpine3.19
          name: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
